// config.bin - 17:40:50 06/26/22, generated in 0.19 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

#define private		0
#define protected		1
#define public		2

#define true	1
#define false	0

class CfgPatches {
	class NM_HMMWV {
		units[] = {};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_Vehicles_Wheeled", "DZ_Vehicles_Parts", "DZ_Sounds_Effects", "DZ_Data"};
	};
};

class CfgMods {
	class NM_HMMWV {
		dir = NM_HMMWV;
		picture = "";
		action = "";
		hideName = 1;
		hidePicture = 1;
		name = NM_HMMWV;
		credits = "NeonMurder";
		author = "NeonMurder";
		authorID = 76561198102181067;
		version = 1;
		extra = 0;
		type = "mod";
		dependencies[] = {"World"};
		
		class defs {
			class worldScriptModule {
				value = "";
				files[] = {"NM_HMMWV/scripts/HMMWV"};
			};
		};
	};
};

class CfgSlots {
	class Slot_Hmmwv_M1035_Wheel_1_1 {
		name = "Hmmwv_M1035_Wheel_1_1";
		displayName = "#STR_Slot_Hmmwv_M1035_Wheel_1_1";
		selection = "wheel_1_1";
		ghostIcon = "wheel";
	};
	
	class Slot_Hmmwv_M1035_Wheel_1_2 {
		name = "Hmmwv_M1035_Wheel_1_2";
		displayName = "#STR_Slot_Hmmwv_M1035_Wheel_1_2";
		selection = "wheel_1_2";
		ghostIcon = "wheel";
	};
	
	class Slot_Hmmwv_M1035_Wheel_2_1 {
		name = "Hmmwv_M1035_Wheel_2_1";
		displayName = "#STR_Slot_Hmmwv_M1035_Wheel_2_1";
		selection = "wheel_2_1";
		ghostIcon = "wheel";
	};
	
	class Slot_Hmmwv_M1035_Wheel_2_2 {
		name = "Hmmwv_M1035_Wheel_2_2";
		displayName = "#STR_Slot_Hmmwv_M1035_Wheel_2_2";
		selection = "wheel_2_2";
		ghostIcon = "wheel";
	};
	
	class Slot_Hmmwv_M1035_Wheel_spare_1 {
		name = "Hmmwv_M1035_Wheel_spare_1";
		displayName = "#STR_Slot_Hmmwv_M1035_Wheel_spare_1";
		selection = "wheel_spare_1";
		ghostIcon = "wheel";
	};
	
	class Slot_Hmmwv_M1035_doors_Driver {
		name = "Hmmwv_M1035_doors_Driver";
		displayName = "#STR_Slot_Hmmwv_M1035_doors_Driver";
		selection = "doors_driver";
		ghostIcon = "doorfront";
	};
	
	class Slot_Hmmwv_M1035_Doors_coDriver {
		name = "Hmmwv_M1035_Doors_coDriver";
		displayName = "#STR_Slot_Hmmwv_M1035_Doors_coDriver";
		selection = "doors_codriver";
		ghostIcon = "doorfront";
	};
	
	class Slot_Hmmwv_M1035_doors_cargo1 {
		name = "Hmmwv_M1035_doors_cargo1";
		displayName = "#STR_Slot_Hmmwv_M1035_doors_cargo1";
		selection = "doors_cargo1";
		ghostIcon = "doorrear";
	};
	
	class Slot_Hmmwv_M1035_doors_cargo2 {
		name = "Hmmwv_M1035_doors_cargo2";
		displayName = "#STR_Slot_Hmmwv_M1035_doors_cargo2";
		selection = "doors_cargo2";
		ghostIcon = "doorrear";
	};
	
	class Slot_Hmmwv_M1035_doors_hood {
		name = "Hmmwv_M1035_doors_hood";
		displayName = "#STR_Slot_Hmmwv_M1035_doors_hood";
		selection = "doors_Hood";
		ghostIcon = "hood";
	};
	
	class Slot_Hmmwv_M1151_doors_Driver {
		name = "Hmmwv_M1151_doors_Driver";
		displayName = "#STR_Slot_Hmmwv_M1035_doors_Driver";
		selection = "doors_driver";
		ghostIcon = "doorfront";
	};
	
	class Slot_Hmmwv_M1151_Doors_coDriver {
		name = "Hmmwv_M1151_Doors_coDriver";
		displayName = "#STR_Slot_Hmmwv_M1035_Doors_coDriver";
		selection = "doors_codriver";
		ghostIcon = "doorfront";
	};
	
	class Slot_Hmmwv_M1151_doors_cargo1 {
		name = "Hmmwv_M1151_doors_cargo1";
		displayName = "#STR_Slot_Hmmwv_M1035_doors_cargo1";
		selection = "doors_cargo1";
		ghostIcon = "doorrear";
	};
	
	class Slot_Hmmwv_M1151_doors_cargo2 {
		name = "Hmmwv_M1151_doors_cargo2";
		displayName = "#STR_Slot_Hmmwv_M1035_doors_cargo2";
		selection = "doors_cargo2";
		ghostIcon = "doorrear";
	};
	
	class Slot_Hmmwv_M1151_doors_trunk {
		name = "Hmmwv_M1151_doors_trunk";
		displayName = "#STR_Slot_Hmmwv_M1151_doors_trunk";
		selection = "doors_Trunk";
		ghostIcon = "trunk";
	};
	
	class Slot_CanisterGasoline {
		name = "CanisterGasoline";
		displayName = "#STR_Slot_CanisterGasoline";
		selection = "CanisterGasoline";
		ghostIcon = "gascanister";
	};
};

class CfgVehicles {
	class Inventory_Base;	// External class reference
	class DamageSystem;	// External class reference
	class GlobalHealth;	// External class reference
	class Health;	// External class reference
	class DamageZones;	// External class reference
	class CarWheel;	// External class reference
	class CarDoor;	// External class reference
	class Window;	// External class reference
	class Doors;	// External class reference
	class CarScript;	// External class reference
	class Crew;	// External class reference
	class Driver;	// External class reference
	class CoDriver;	// External class reference
	class SimulationModule;	// External class reference
	class Axles;	// External class reference
	class Front;	// External class reference
	class Rear;	// External class reference
	class Left;	// External class reference
	class Right;	// External class reference
	class Wheels;	// External class reference
	class Bottle_Base;	// External class reference
	
	class CanisterGasoline : Bottle_Base {
		inventorySlot = "CanisterGasoline";
	};
	
	class Hmmwv_M1035_Wheel : CarWheel {
		scope = public;
		model = "NM_Hmmwv\proxy\Hmmwv_M1035_Wheel.p3d";
		displayName = "#STR_Hmmwv_M1035_Wheel";
		descriptionShort = "#STR_Hmmwv_M1035_Wheel_Descr";
		itemSize[] = {10, 10};
		weight = 20000;
		inventorySlot[] = {"Hmmwv_M1035_Wheel_1_1", "Hmmwv_M1035_Wheel_1_2", "Hmmwv_M1035_Wheel_2_1", "Hmmwv_M1035_Wheel_2_2", "Hmmwv_M1035_Wheel_spare_1"};
		rotationFlags = 8;
		physLayer = "item_large";
		radiusByDamage[] = {0, 0.39, 0.3, 0.3, 0.9998, 0.25, 0.9999, 0.2};
		radius = 0.46;
		friction = 0.96;
		width = 0.26;
		tyreRollResistance = 0.01;
		tyreTread = 2;
	};
	
	class Hmmwv_M1035_Wheel_destroyed : Hmmwv_M1035_Wheel {
		model = "NM_Hmmwv\proxy\Hmmwv_M1035_Wheel_destroyed.p3d";
		weight = 10000;
		itemSize[] = {6, 6};
		itemBehaviour = 0;
		rotationFlags = 4;
		physLayer = "item_large";
		tyreRollResistance = 1;
		tyreRollDrag = 70;
		tyreRoughness = 1;
		tyreTread = 0.4;
		radius = 0.154;
		width = 0.234;
		friction = -1;
	};
	
	class Hmmwv_M1035_doors_Driver : CarDoor {
		scope = public;
		displayName = "#STR_Hmmwv_M1035_doors_Driver";
		descriptionShort = "#STR_Hmmwv_M1035_doors_Driver";
		model = "NM_Hmmwv\proxy\Hmmwv_M1035_doors_Driver.p3d";
		weight = 15000;
		itemSize[] = {10, 10};
		itemBehaviour = 0;
		inventorySlot = "Hmmwv_M1035_doors_Driver";
		rotationFlags = 8;
		physLayer = "item_large";
	};
	
	class Hmmwv_M1035_Doors_coDriver : Hmmwv_M1035_doors_Driver {
		displayName = "#STR_Hmmwv_M1035_Doors_coDriver";
		descriptionShort = "#STR_Hmmwv_M1035_Doors_coDriver";
		model = "NM_Hmmwv\proxy\Hmmwv_M1035_Doors_coDriver.p3d";
		inventorySlot = "Hmmwv_M1035_Doors_coDriver";
	};
	
	class Hmmwv_M1035_doors_cargo1 : Hmmwv_M1035_doors_Driver {
		displayName = "#STR_Hmmwv_M1035_doors_cargo1";
		descriptionShort = "#STR_Hmmwv_M1035_doors_cargo1";
		model = "NM_Hmmwv\proxy\Hmmwv_M1035_doors_cargo1.p3d";
		inventorySlot = "Hmmwv_M1035_doors_cargo1";
	};
	
	class Hmmwv_M1035_doors_cargo2 : Hmmwv_M1035_doors_Driver {
		displayName = "#STR_Hmmwv_M1035_doors_cargo2";
		descriptionShort = "#STR_Hmmwv_M1035_doors_cargo2";
		model = "NM_Hmmwv\proxy\Hmmwv_M1035_doors_cargo2.p3d";
		inventorySlot = "Hmmwv_M1035_doors_cargo2";
	};
	
	class Hmmwv_M1035_doors_Driver_Green : Hmmwv_M1035_doors_Driver {
		hiddenSelections[] = {"camo_d_d"};
		hiddenSelectionsTextures[] = {"NM_Hmmwv\data\hmmwv_canvas_1_green_co.paa"};
		hiddenSelectionsMaterials[] = {"NM_Hmmwv\data\hmmwv_canvas.rvmat"};
	};
	
	class Hmmwv_M1035_Doors_coDriver_Green : Hmmwv_M1035_Doors_coDriver {
		hiddenSelections[] = {"camo_d_cd"};
		hiddenSelectionsTextures[] = {"NM_Hmmwv\data\hmmwv_canvas_1_green_co.paa"};
		hiddenSelectionsMaterials[] = {"NM_Hmmwv\data\hmmwv_canvas.rvmat"};
	};
	
	class Hmmwv_M1035_doors_cargo1_Green : Hmmwv_M1035_doors_cargo1 {
		hiddenSelections[] = {"camo_d_c1"};
		hiddenSelectionsTextures[] = {"NM_Hmmwv\data\hmmwv_canvas_1_green_co.paa"};
		hiddenSelectionsMaterials[] = {"NM_Hmmwv\data\hmmwv_canvas.rvmat"};
	};
	
	class Hmmwv_M1035_doors_cargo2_Green : Hmmwv_M1035_doors_cargo2 {
		hiddenSelections[] = {"camo_d_c2"};
		hiddenSelectionsTextures[] = {"NM_Hmmwv\data\hmmwv_canvas_1_green_co.paa"};
		hiddenSelectionsMaterials[] = {"NM_Hmmwv\data\hmmwv_canvas.rvmat"};
	};
	
	class Hmmwv_M1035_doors_Driver_Gray : Hmmwv_M1035_doors_Driver {
		hiddenSelections[] = {"camo_d_d"};
		hiddenSelectionsTextures[] = {"NM_Hmmwv\data\hmmwv_canvas_1_gray_co.paa"};
		hiddenSelectionsMaterials[] = {"NM_Hmmwv\data\hmmwv_canvas.rvmat"};
	};
	
	class Hmmwv_M1035_Doors_coDriver_Gray : Hmmwv_M1035_Doors_coDriver {
		hiddenSelections[] = {"camo_d_cd"};
		hiddenSelectionsTextures[] = {"NM_Hmmwv\data\hmmwv_canvas_1_gray_co.paa"};
		hiddenSelectionsMaterials[] = {"NM_Hmmwv\data\hmmwv_canvas.rvmat"};
	};
	
	class Hmmwv_M1035_doors_cargo1_Gray : Hmmwv_M1035_doors_cargo1 {
		hiddenSelections[] = {"camo_d_c1"};
		hiddenSelectionsTextures[] = {"NM_Hmmwv\data\hmmwv_canvas_1_gray_co.paa"};
		hiddenSelectionsMaterials[] = {"NM_Hmmwv\data\hmmwv_canvas.rvmat"};
	};
	
	class Hmmwv_M1035_doors_cargo2_Gray : Hmmwv_M1035_doors_cargo2 {
		hiddenSelections[] = {"camo_d_c2"};
		hiddenSelectionsTextures[] = {"NM_Hmmwv\data\hmmwv_canvas_1_gray_co.paa"};
		hiddenSelectionsMaterials[] = {"NM_Hmmwv\data\hmmwv_canvas.rvmat"};
	};
	
	class Hmmwv_M1035_doors_Driver_Black : Hmmwv_M1035_doors_Driver {
		hiddenSelections[] = {"camo_d_d"};
		hiddenSelectionsTextures[] = {"NM_Hmmwv\data\hmmwv_canvas_1_black_co.paa"};
		hiddenSelectionsMaterials[] = {"NM_Hmmwv\data\hmmwv_canvas.rvmat"};
	};
	
	class Hmmwv_M1035_Doors_coDriver_Black : Hmmwv_M1035_Doors_coDriver {
		hiddenSelections[] = {"camo_d_cd"};
		hiddenSelectionsTextures[] = {"NM_Hmmwv\data\hmmwv_canvas_1_black_co.paa"};
		hiddenSelectionsMaterials[] = {"NM_Hmmwv\data\hmmwv_canvas.rvmat"};
	};
	
	class Hmmwv_M1035_doors_cargo1_Black : Hmmwv_M1035_doors_cargo1 {
		hiddenSelections[] = {"camo_d_c1"};
		hiddenSelectionsTextures[] = {"NM_Hmmwv\data\hmmwv_canvas_1_black_co.paa"};
		hiddenSelectionsMaterials[] = {"NM_Hmmwv\data\hmmwv_canvas.rvmat"};
	};
	
	class Hmmwv_M1035_doors_cargo2_Black : Hmmwv_M1035_doors_cargo2 {
		hiddenSelections[] = {"camo_d_c2"};
		hiddenSelectionsTextures[] = {"NM_Hmmwv\data\hmmwv_canvas_1_black_co.paa"};
		hiddenSelectionsMaterials[] = {"NM_Hmmwv\data\hmmwv_canvas.rvmat"};
	};
	
	class Hmmwv_M1151_doors_Driver : CarDoor {
		scope = public;
		displayName = "#STR_Hmmwv_M1151_doors_Driver";
		descriptionShort = "#STR_Hmmwv_M1151_doors_Driver";
		model = "NM_Hmmwv\proxy\Hmmwv_M1151_doors_Driver.p3d";
		weight = 15000;
		itemSize[] = {10, 10};
		itemBehaviour = 0;
		inventorySlot = "Hmmwv_M1151_doors_Driver";
		rotationFlags = 8;
		physLayer = "item_large";
	};
	
	class Hmmwv_M1151_Doors_coDriver : Hmmwv_M1035_doors_Driver {
		displayName = "#STR_Hmmwv_M1151_Doors_coDriver";
		descriptionShort = "#STR_Hmmwv_M1151_Doors_coDriver";
		model = "NM_Hmmwv\proxy\Hmmwv_M1151_Doors_coDriver.p3d";
		inventorySlot = "Hmmwv_M1151_Doors_coDriver";
	};
	
	class Hmmwv_M1151_doors_cargo1 : Hmmwv_M1035_doors_Driver {
		displayName = "#STR_Hmmwv_M1151_doors_cargo1";
		descriptionShort = "#STR_Hmmwv_M1151_doors_cargo1";
		model = "NM_Hmmwv\proxy\Hmmwv_M1151_doors_cargo1.p3d";
		inventorySlot = "Hmmwv_M1151_doors_cargo1";
	};
	
	class Hmmwv_M1151_doors_cargo2 : Hmmwv_M1035_doors_Driver {
		displayName = "#STR_Hmmwv_M1151_doors_cargo2";
		descriptionShort = "#STR_Hmmwv_M1151_doors_cargo2";
		model = "NM_Hmmwv\proxy\Hmmwv_M1151_doors_cargo2.p3d";
		inventorySlot = "Hmmwv_M1151_doors_cargo2";
	};
	
	class Hmmwv_M1151_doors_Driver_Green : Hmmwv_M1151_doors_Driver {
		hiddenSelections[] = {"camo_d_d1151"};
		hiddenSelectionsTextures[] = {"NM_Hmmwv\data\hmmwv_gpk_tower_green_co.paa"};
		hiddenSelectionsMaterials[] = {"NM_Hmmwv\data\hmmwv_gpk_tower.rvmat"};
	};
	
	class Hmmwv_M1151_Doors_coDriver_Green : Hmmwv_M1151_Doors_coDriver {
		hiddenSelections[] = {"camo_d_cd1151"};
		hiddenSelectionsTextures[] = {"NM_Hmmwv\data\hmmwv_gpk_tower_green_co.paa"};
		hiddenSelectionsMaterials[] = {"NM_Hmmwv\data\hmmwv_gpk_tower.rvmat"};
	};
	
	class Hmmwv_M1151_doors_cargo1_Green : Hmmwv_M1151_doors_cargo1 {
		hiddenSelections[] = {"camo_d_c11151"};
		hiddenSelectionsTextures[] = {"NM_Hmmwv\data\hmmwv_gpk_tower_green_co.paa"};
		hiddenSelectionsMaterials[] = {"NM_Hmmwv\data\hmmwv_gpk_tower.rvmat"};
	};
	
	class Hmmwv_M1151_doors_cargo2_Green : Hmmwv_M1151_doors_cargo2 {
		hiddenSelections[] = {"camo_d_c21151"};
		hiddenSelectionsTextures[] = {"NM_Hmmwv\data\hmmwv_gpk_tower_green_co.paa"};
		hiddenSelectionsMaterials[] = {"NM_Hmmwv\data\hmmwv_gpk_tower.rvmat"};
	};
	
	class Hmmwv_M1151_doors_Driver_Gray : Hmmwv_M1151_doors_Driver {
		hiddenSelections[] = {"camo_d_d1151"};
		hiddenSelectionsTextures[] = {"NM_Hmmwv\data\hmmwv_gpk_tower_gray_co.paa"};
		hiddenSelectionsMaterials[] = {"NM_Hmmwv\data\hmmwv_gpk_tower.rvmat"};
	};
	
	class Hmmwv_M1151_Doors_coDriver_Gray : Hmmwv_M1151_Doors_coDriver {
		hiddenSelections[] = {"camo_d_cd1151"};
		hiddenSelectionsTextures[] = {"NM_Hmmwv\data\hmmwv_gpk_tower_gray_co.paa"};
		hiddenSelectionsMaterials[] = {"NM_Hmmwv\data\hmmwv_gpk_tower.rvmat"};
	};
	
	class Hmmwv_M1151_doors_cargo1_Gray : Hmmwv_M1151_doors_cargo1 {
		hiddenSelections[] = {"camo_d_c11151"};
		hiddenSelectionsTextures[] = {"NM_Hmmwv\data\hmmwv_gpk_tower_gray_co.paa"};
		hiddenSelectionsMaterials[] = {"NM_Hmmwv\data\hmmwv_gpk_tower.rvmat"};
	};
	
	class Hmmwv_M1151_doors_cargo2_Gray : Hmmwv_M1151_doors_cargo2 {
		hiddenSelections[] = {"camo_d_c21151"};
		hiddenSelectionsTextures[] = {"NM_Hmmwv\data\hmmwv_gpk_tower_gray_co.paa"};
		hiddenSelectionsMaterials[] = {"NM_Hmmwv\data\hmmwv_gpk_tower.rvmat"};
	};
	
	class Hmmwv_M1151_doors_Driver_Black : Hmmwv_M1151_doors_Driver {
		hiddenSelections[] = {"camo_d_d1151"};
		hiddenSelectionsTextures[] = {"NM_Hmmwv\data\hmmwv_gpk_tower_black_co.paa"};
		hiddenSelectionsMaterials[] = {"NM_Hmmwv\data\hmmwv_gpk_tower.rvmat"};
	};
	
	class Hmmwv_M1151_Doors_coDriver_Black : Hmmwv_M1151_Doors_coDriver {
		hiddenSelections[] = {"camo_d_cd1151"};
		hiddenSelectionsTextures[] = {"NM_Hmmwv\data\hmmwv_gpk_tower_black_co.paa"};
		hiddenSelectionsMaterials[] = {"NM_Hmmwv\data\hmmwv_gpk_tower.rvmat"};
	};
	
	class Hmmwv_M1151_doors_cargo1_Black : Hmmwv_M1151_doors_cargo1 {
		hiddenSelections[] = {"camo_d_c11151"};
		hiddenSelectionsTextures[] = {"NM_Hmmwv\data\hmmwv_gpk_tower_black_co.paa"};
		hiddenSelectionsMaterials[] = {"NM_Hmmwv\data\hmmwv_gpk_tower.rvmat"};
	};
	
	class Hmmwv_M1151_doors_cargo2_Black : Hmmwv_M1151_doors_cargo2 {
		hiddenSelections[] = {"camo_d_c21151"};
		hiddenSelectionsTextures[] = {"NM_Hmmwv\data\hmmwv_gpk_tower_black_co.paa"};
		hiddenSelectionsMaterials[] = {"NM_Hmmwv\data\hmmwv_gpk_tower.rvmat"};
	};
	
	class Hmmwv_M1035_doors_hood : CarDoor {
		scope = public;
		displayName = "#STR_Hmmwv_M1035_doors_hood";
		descriptionShort = "#STR_Hmmwv_M1035_Wheel_Descr";
		model = "NM_Hmmwv\proxy\Hmmwv_M1035_doors_hood.p3d";
		weight = 10000;
		itemSize[] = {10, 10};
		itemBehaviour = 0;
		inventorySlot = "Hmmwv_M1035_doors_hood";
		rotationFlags = 4;
		physLayer = "item_large";
	};
	
	class Hmmwv_M1035_doors_hood_Green : Hmmwv_M1035_doors_hood {
		hiddenSelections[] = {"camo1"};
		hiddenSelectionsTextures[] = {"NM_Hmmwv\data\hmmwv_hood_canvas_green_co.paa"};
		hiddenSelectionsMaterials[] = {"NM_Hmmwv\data\hmmwv_hood.rvmat"};
	};
	
	class Hmmwv_M1035_doors_hood_Gray : Hmmwv_M1035_doors_hood {
		hiddenSelections[] = {"camo1"};
		hiddenSelectionsTextures[] = {"NM_Hmmwv\data\hmmwv_hood_canvas_gray_co.paa"};
		hiddenSelectionsMaterials[] = {"NM_Hmmwv\data\hmmwv_hood.rvmat"};
	};
	
	class Hmmwv_M1035_doors_hood_Black : Hmmwv_M1035_doors_hood {
		hiddenSelections[] = {"camo1"};
		hiddenSelectionsTextures[] = {"NM_Hmmwv\data\hmmwv_hood_canvas_black_co.paa"};
		hiddenSelectionsMaterials[] = {"NM_Hmmwv\data\hmmwv_hood.rvmat"};
	};
	
	class Hmmwv_M1151_doors_trunk : CarDoor {
		scope = public;
		displayName = "#STR_Hmmwv_M1151_doors_trunk";
		descriptionShort = "#STR_Hmmwv_M1151_doors_trunk";
		model = "NM_Hmmwv\proxy\Hmmwv_M1151_doors_trunk.p3d";
		weight = 10000;
		itemSize[] = {10, 10};
		itemBehaviour = 0;
		inventorySlot = "Hmmwv_M1151_doors_trunk";
		rotationFlags = 4;
		physLayer = "item_large";
	};
	
	class Hmmwv_M1151_doors_trunk_Green : Hmmwv_M1151_doors_trunk {
		hiddenSelections[] = {"camo_d_t"};
		hiddenSelectionsTextures[] = {"NM_Hmmwv\data\hmmwv_regular_1_green_co.paa"};
		hiddenSelectionsMaterials[] = {"NM_Hmmwv\data\hmmwv_regular_gpk.rvmat"};
	};
	
	class Hmmwv_M1151_doors_trunk_Gray : Hmmwv_M1151_doors_trunk {
		hiddenSelections[] = {"camo_d_t"};
		hiddenSelectionsTextures[] = {"NM_Hmmwv\data\hmmwv_regular_1_gray_co.paa"};
		hiddenSelectionsMaterials[] = {"NM_Hmmwv\data\hmmwv_regular_gpk.rvmat"};
	};
	
	class Hmmwv_M1151_doors_trunk_Black : Hmmwv_M1151_doors_trunk {
		hiddenSelections[] = {"camo_d_t"};
		hiddenSelectionsTextures[] = {"NM_Hmmwv\data\hmmwv_regular_1_black_co.paa"};
		hiddenSelectionsMaterials[] = {"NM_Hmmwv\data\hmmwv_regular_gpk.rvmat"};
	};
	
	class Hmmwv_M1035 : CarScript {
		scope = public;
		displayname = "#STR_Hmmwv_M1035";
		descriptionShort = "";
		model = "\NM_Hmmwv\Hmmwv_M1035.p3d";
		InteractActions[] = {AT_GETIN_TRANSPORT};
		attachments[] = {"CarBattery", "Reflector_1_1", "Reflector_2_1", "CarRadiator", "SparkPlug", "CanisterGasoline", "Hmmwv_M1035_Wheel_1_1", "Hmmwv_M1035_Wheel_1_2", "Hmmwv_M1035_Wheel_2_1", "Hmmwv_M1035_Wheel_2_2", "Hmmwv_M1035_Wheel_spare_1", "Hmmwv_M1035_doors_Driver", "Hmmwv_M1035_Doors_coDriver", "Hmmwv_M1035_doors_cargo1", "Hmmwv_M1035_doors_cargo2", "Hmmwv_M1035_doors_hood"};
		hiddenSelections[] = {"light_1_1", "light_2_1", "light_brake_1_2", "light_brake_2_2", "light_reverse_1_2", "light_reverse_2_2", "light_1_2", "light_2_2", "light_dashboard"};
		hiddenSelectionsTextures[] = {"", "", "", "", "", "", "", "", ""};
		hiddenSelectionsMaterials[] = {"", "", "", "", "", "", "", "", ""};
		dashboardMatOn = "NM_Hmmwv\data\dashboard_on.rvmat";
		dashboardMatOff = "NM_Hmmwv\data\dashboard.rvmat";
		frontReflectorMatOn = "NM_Hmmwv\data\light_on.rvmat";
		frontReflectorMatOff = "NM_Hmmwv\data\light.rvmat";
		brakeReflectorMatOn = "NM_Hmmwv\data\light_on.rvmat";
		brakeReflectorMatOff = "NM_Hmmwv\data\light.rvmat";
		ReverseReflectorMatOn = "NM_Hmmwv\data\light_on.rvmat";
		ReverseReflectorMatOff = "NM_Hmmwv\data\light.rvmat";
		TailReflectorMatOn = "dz\vehicles\wheeled\civiliansedan\data\Sedan_TailLights_e.rvmat";
		TailReflectorMatOff = "dz\vehicles\wheeled\civiliansedan\data\Sedan_TailLights.rvmat";
		weight = 1400000;
		rotationFlags = 64;
		insideSoundCoef = 0.9;
		brakeFluidCapacity = 1;
		oilCapacity = 4;
		coolantCapacity = 6;
		brakeFluidLeakDebit[] = {0, 0};
		oilLeakDebit[] = {0, 0};
		coolantLeakDebit[] = {0, 0};
		brakeFluidForceCoef[] = {0, 1, 1, 1};
		damageFromOil[] = {0, 0, 1, 0};
		damageFromCoolant[] = {0, 0, 1, 0};
		engineBeltSlot = "EngineBelt";
		batterySlot = "CarBattery";
		electricPowerResName = "power";
		electricConsumptionIgnition = 3001;
		electricConsumptionEngine = 0;
		electricConsumptionLights = 0;
		electricOutputEngine = 5;
		selectionDashboard = "light_dashboard";
		selectionLightFrontL = "light_left";
		selectionLightFrontR = "light_right";
		selectionBrakeLights = "light_break";
		fuelCapacity = 43;
		fuelConsumption = 10;
		
		class Sounds {
			thrust = 0.6;
			thrustTurbo = 1;
			thrustGentle = 0.3;
			thrustSmoothCoef = 0.1;
			camposSmoothCoef = 0.03;
			soundSetsFilter[] = {"Hmmwv_M1035_Engine_Offload_Ext_Rpm1_SoundSet", "Hmmwv_M1035_Engine_Offload_Ext_Rpm2_SoundSet", "Hmmwv_M1035_Engine_Offload_Ext_Rpm3_SoundSet", "Hmmwv_M1035_Engine_Offload_Ext_Rpm4_SoundSet", "Hmmwv_M1035_Engine_Offload_Ext_Rpm5_SoundSet", "Hmmwv_M1035_Engine_Ext_Rpm0_SoundSet", "Hmmwv_M1035_Engine_Ext_Rpm1_SoundSet", "Hmmwv_M1035_Engine_Ext_Rpm2_SoundSet", "Hmmwv_M1035_Engine_Ext_Rpm3_SoundSet", "Hmmwv_M1035_Engine_Ext_Rpm4_SoundSet", "Hmmwv_M1035_Engine_Ext_Rpm5_SoundSet", "Hmmwv_M1035_Engine_Ext_Broken_SoundSet", "offroad_Tires_rock_slow_Ext_SoundSet", "offroad_Tires_rock_fast_Ext_SoundSet", "offroad_Tires_grass_slow_Ext_SoundSet", "offroad_Tires_grass_fast_Ext_SoundSet", "offroad_Tires_gravel_slow_Ext_SoundSet", "offroad_Tires_gravel_fast_Ext_SoundSet", "offroad_Tires_asphalt_slow_Ext_SoundSet", "offroad_Tires_asphalt_fast_Ext_SoundSet", "offroad_Tires_water_slow_Ext_SoundSet", "offroad_Tires_water_fast_Ext_SoundSet", "offroad_skid_dirt_SoundSet", "offroad_dirt_turn_SoundSet", "offroad_Rain_Ext_SoundSet"};
			soundSetsInt[] = {"offroad_Tires_Asphalt_Slow_General_Int_SoundSet", "offroad_Tires_Asphalt_Fast_General_Int_SoundSet", "offroad_Wind_SoundSet"};
		};
		
		class Crew : Crew {
			class Driver : Driver {};
			
			class CoDriver : CoDriver {};
			
			class Cargo1 {
				actionSel = "seat_cargo1";
				proxyPos = "crewCargo1";
				getInPos = "pos_cargo1";
				getInDir = "pos_cargo1_dir";
			};
			
			class Cargo2 {
				actionSel = "seat_cargo2";
				proxyPos = "crewCargo2";
				getInPos = "pos_cargo2";
				getInDir = "pos_cargo2_dir";
			};
		};
		
		class SimulationModule : SimulationModule {
			drive = DRIVE_AWD;
			centralDiffRatio = 1.45;
			airDragCoefficient = 2;
			
			class Steering {
				increaseSpeed[] = {0, 45, 60, 25, 100, 15};
				decreaseSpeed[] = {0, 90, 60, 45, 100, 15};
				centeringSpeed[] = {0, 0, 15, 28, 60, 45, 100, 60};
			};
			
			class Throttle {
				reactionTime = 1.5;
				defaultThrust = 0.95;
				gentleThrust = 0.7;
				turboCoef = 4.5;
				gentleCoef = 0.76;
			};
			braking[] = {0, 0.1, 1, 0.8, 2.5, 0.9, 3, 1};
			
			class Engine {
				inertia = 0.15;
				steepness = 1.5;
				torqueMax = 320;
				torqueRpm = 3400;
				powerMax = 53.7;
				powerRpm = 5400;
				rpmIdle = 850;
				rpmMin = 900;
				rpmClutch = 1350;
				rpmRedline = 6000;
				rpmMax = 8000;
			};
			
			class Gearbox {
				reverse = 3.46;
				ratios[] = {3.667, 2.1, 1.361, 1};
				timeToUncoupleClutch = 0.15;
				timeToCoupleClutch = 0.21;
				maxClutchTorque = 250;
			};
			
			class Axles : Axles {
				class Front : Front {
					maxSteeringAngle = 40;
					finalRatio = 4.6;
					brakeBias = 0.6;
					brakeForce = 5000;
					wheelHubMass = 5;
					wheelHubRadius = 0.15;
					
					class Suspension {
						swayBar = 3000;
						stiffness = 36180;
						compression = 3400;
						damping = 7600;
						travelMaxUp = 0.3;
						travelMaxDown = 0.07;
					};
					
					class Wheels : Wheels {
						class Left : Left {
							animDamper = "damper_1_1";
							inventorySlot = "Hmmwv_M1035_Wheel_1_1";
						};
						
						class Right : Right {
							animDamper = "damper_2_1";
							inventorySlot = "Hmmwv_M1035_Wheel_2_1";
						};
					};
				};
				
				class Rear : Rear {
					maxSteeringAngle = 0;
					finalRatio = 4.6;
					brakeBias = 0.6;
					brakeForce = 4600;
					wheelHubMass = 5;
					wheelHubRadius = 0.15;
					
					class Suspension {
						swayBar = 3000;
						stiffness = 36180;
						compression = 3400;
						damping = 7600;
						travelMaxUp = 0.3;
						travelMaxDown = 0.07;
					};
					
					class Wheels : Wheels {
						class Left : Left {
							animDamper = "damper_1_2";
							inventorySlot = "Hmmwv_M1035_Wheel_1_2";
						};
						
						class Right : Right {
							animDamper = "damper_2_2";
							inventorySlot = "Hmmwv_M1035_Wheel_2_2";
						};
					};
				};
			};
		};
		
		class Cargo {
			itemsCargoSize[] = {10, 100};
			allowOwnedCargoManipulation = 1;
			openable = 0;
		};
		
		class DamageSystem {
			class GlobalHealth {
				class Health {
					hitpoints = 8700;
					healthLevels[] = {{1, {}}, {0.7, {}}, {0.5, {}}, {0.3, {}}, {0, {}}};
				};
			};
			
			class DamageZones {
				class Chassis {
					class Health {
						hitpoints = 8700;
						transferToGlobalCoef = 1;
					};
					componentNames[] = {"dmgZone_chassis"};
					fatalInjuryCoef = -1;
					inventorySlots[] = {};
				};
				
				class Front {
					class Health {
						hitpoints = 2700;
						transferToGlobalCoef = 0;
						healthLevels[] = {{1, {}}, {0.7, {}}, {0.5, {}}, {0.3, {}}, {0, {}}};
					};
					transferToZonesNames[] = {"Fender_1_1", "Fender_2_1", "Engine", "Reflector_1_1", "Reflector_2_1", "WindowFront"};
					transferToZonesThreshold[] = {0.8, 0.8, 0.5, 1, 1, 0.5};
					transferToZonesCoefs[] = {0.6, 0.6, 0.6, 0.05, 0.05};
					memoryPoints[] = {"dmgZone_front"};
					componentNames[] = {"dmgZone_front"};
					fatalInjuryCoef = -1;
					inventorySlotsCoefs[] = {0.15, 0.3};
					inventorySlots[] = {"CarRadiator", "Hmmwv_M1035_doors_hood"};
				};
				
				class Reflector_1_1 {
					class Health {
						hitpoints = 10;
						transferToGlobalCoef = 0;
						healthLevels[] = {{1, {}}, {0.7, {}}, {0.5, {}}, {0.3, {}}, {0, {}}};
					};
					transferToZonesNames[] = {"Front", "Fender_1_1", "Engine"};
					transferToZonesCoefs[] = {1, 1, 1};
					memoryPoints[] = {"dmgZone_lights_1_1"};
					componentNames[] = {"dmgZone_lights_1_1"};
					fatalInjuryCoef = -1;
					inventorySlotsCoefs[] = {1, 0.3, 0.3};
					inventorySlots[] = {"Reflector_1_1"};
				};
				
				class Reflector_2_1 : Reflector_1_1 {
					transferToZonesNames[] = {"Front", "Fender_2_1", "Engine"};
					transferToZonesCoefs[] = {1, 1, 1};
					memoryPoints[] = {"dmgZone_lights_2_1"};
					componentNames[] = {"dmgZone_lights_2_1"};
					inventorySlotsCoefs[] = {1, 0.3, 0.3};
					inventorySlots[] = {"Reflector_2_1"};
				};
				
				class Back {
					class Health {
						hitpoints = 2700;
						transferToGlobalCoef = 0;
						healthLevels[] = {{1, {}}, {0.7, {}}, {0.5, {}}, {0.3, {}}, {0, {}}};
					};
					transferToZonesNames[] = {"Fender_1_2", "Fender_2_2"};
					transferToZonesCoefs[] = {0.3, 0.3};
					memoryPoints[] = {"dmgZone_back"};
					componentNames[] = {"dmgZone_back"};
					fatalInjuryCoef = -1;
					inventorySlotsCoefs[] = {0.3};
					inventorySlots[] = {"Hmmwv_M1035_doors_trunk"};
				};
				
				class Roof {
					class Health {
						hitpoints = 2300;
						transferToGlobalCoef = 0;
						healthLevels[] = {{1, {}}, {0.7, {}}, {0.5, {}}, {0.3, {}}, {0, {}}};
					};
					memoryPoints[] = {"dmgZone_roof"};
					componentNames[] = {"dmgZone_roof"};
					fatalInjuryCoef = -1;
					inventorySlots[] = {};
				};
				
				class Fender_1_1 {
					class Health {
						hitpoints = 2400;
						transferToGlobalCoef = 0;
						healthLevels[] = {{1, {}}, {0.7, {}}, {0.5, {}}, {0.3, {}}, {0, {}}};
					};
					transferToZonesNames[] = {"Front", "Engine", "Reflector_1_1"};
					transferToZonesThreshold[] = {0.2, 0.5, 0.9};
					transferToZonesCoefs[] = {0.3, 0.6, 0.6};
					memoryPoints[] = {"dmgZone_fender_1_1"};
					componentNames[] = {"dmgZone_fender_1_1"};
					fatalInjuryCoef = -1;
					inventorySlotsCoefs[] = {0.3, 0.3, 0.3};
					inventorySlots[] = {""};
				};
				
				class Fender_2_1 : Fender_1_1 {
					transferToZonesNames[] = {"Front", "Engine", "Reflector_2_1"};
					transferToZonesThreshold[] = {0.2, 0.5, 0.9};
					transferToZonesCoefs[] = {0.3, 0.6, 0.6};
					memoryPoints[] = {"dmgZone_fender_2_1"};
					componentNames[] = {"dmgZone_fender_2_1"};
					inventorySlotsCoefs[] = {0.3, 0.2, 31};
					inventorySlots[] = {""};
				};
				
				class Fender_1_2 : Fender_1_1 {
					transferToZonesNames[] = {"Back", "FuelTank", "WindowBack"};
					transferToZonesThreshold[] = {0.2, 0.2, 0.2};
					transferToZonesCoefs[] = {0.3, 0.2, 0.7};
					memoryPoints[] = {"dmgZone_fender_1_2"};
					componentNames[] = {"dmgZone_fender_1_2"};
					inventorySlotsCoefs[] = {0.3};
					inventorySlots[] = {"Hmmwv_M1035_doors_trunk"};
				};
				
				class Fender_2_2 : Fender_1_1 {
					transferToZonesNames[] = {"Back", "FuelTank", "WindowBack"};
					transferToZonesThreshold[] = {0.2, 0.2, 0.2};
					transferToZonesCoefs[] = {0.3, 0.2, 0.7};
					memoryPoints[] = {"dmgZone_fender_2_2"};
					componentNames[] = {"dmgZone_fender_2_2"};
					inventorySlotsCoefs[] = {0.3};
					inventorySlots[] = {"Hmmwv_M1035_doors_trunk"};
				};
				
				class WindowFront {
					class Health {
						hitpoints = 300;
						transferToGlobalCoef = 0;
						healthLevels[] = {{1, {}}, {0.7, {}}, {0.5, {}}, {0.3, {}}, {0, {}}};
					};
					memoryPoints[] = {"dmgZone_windowFront"};
					componentNames[] = {"dmgZone_windowFront"};
					fatalInjuryCoef = -1;
					inventorySlots[] = {};
				};
				
				class WindowBack {
					class Health {
						hitpoints = 300;
						transferToGlobalCoef = 0;
						healthLevels[] = {{1, {}}, {0.7, {}}, {0.5, {}}, {0.3, {}}, {0, {}}};
					};
					memoryPoints[] = {"dmgZone_windowBack"};
					componentNames[] = {"dmgZone_windowBack"};
					fatalInjuryCoef = -1;
					inventorySlots[] = {};
				};
				
				class Engine {
					class Health {
						hitpoints = 8700;
						transferToGlobalCoef = 0;
						healthLevels[] = {{1, {}}, {0.7, {}}, {0.5, {}}, {0.3, {}}, {0, {}}};
					};
					memoryPoints[] = {"dmgZone_engine"};
					componentNames[] = {"dmgZone_engine"};
					fatalInjuryCoef = 0.001;
					inventorySlotsCoefs[] = {0.2, 0.2, 0.01, 0.4};
					inventorySlots[] = {};
				};
				
				class FuelTank {
					class Health {
						hitpoints = 900;
						transferToGlobalCoef = 0;
						healthLevels[] = {{1, {}}, {0.7, {}}, {0.5, {}}, {0.3, {}}, {0, {}}};
					};
					componentNames[] = {"dmgZone_fuelTank"};
					fatalInjuryCoef = -1;
					inventorySlots[] = {};
				};
				
				class Battery {
					class Health {
						hitpoints = 800;
						transferToGlobalCoef = 0;
						healthLevels[] = {{1, {}}, {0.7, {}}, {0.5, {}}, {0.3, {}}, {0, {}}};
					};
					componentNames[] = {"dmgZone_battery"};
					fatalInjuryCoef = -1;
					inventorySlots[] = {"CarBattery"};
				};
			};
		};
		
		class ObstacleGenerator {
			carve = 1;
			timeToStationary = 5;
			moveThreshold = 0.5;
			
			class Shapes {
				class Cylindric {
					class Cyl1 {
						radius = 1;
						height = 1.5;
						center[] = {0, 0, 0.7};
					};
					
					class Cyl3 {
						radius = 1;
						height = 1.5;
						center[] = {0, 0, -0.7};
					};
				};
			};
		};
		
		class GUIInventoryAttachmentsProps {
			class Engine {
				name = "#STR_Hmmwv_Engine";
				description = "";
				attachmentSlots[] = {"CarBattery", "CarRadiator", "SparkPlug", "Reflector_1_1", "Reflector_2_1"};
				icon = "cat_vehicle_engine";
			};
			
			class Body {
				name = "#STR_Hmmwv_Body";
				description = "";
				attachmentSlots[] = {"Hmmwv_M1035_doors_Driver", "Hmmwv_M1035_Doors_coDriver", "Hmmwv_M1035_doors_cargo1", "Hmmwv_M1035_doors_cargo2", "Hmmwv_M1035_doors_hood"};
				icon = "cat_vehicle_body";
			};
			
			class Chassis {
				name = "#STR_Hmmwv_Chassis";
				description = "";
				attachmentSlots[] = {"Hmmwv_M1035_Wheel_1_1", "Hmmwv_M1035_Wheel_1_2", "Hmmwv_M1035_Wheel_2_1", "Hmmwv_M1035_Wheel_2_2", "Hmmwv_M1035_Wheel_spare_1"};
				icon = "cat_vehicle_chassis";
			};
			
			class Attachments {
				name = "#STR_Hmmwv_Attachments";
				description = "";
				attachmentSlots[] = {"CanisterGasoline"};
				icon = "cat_vehicle_chassis";
			};
		};
		
		class AnimationSources {
			class DoorsDriver {
				source = "user";
				initPhase = 0;
				animPeriod = 0.5;
			};
			
			class DoorsCoDriver : DoorsDriver {};
			
			class DoorsHood : DoorsDriver {};
			
			class DoorsTrunk : DoorsDriver {};
			
			class DoorsCargo1 : DoorsDriver {};
			
			class DoorsCargo2 : DoorsDriver {};
			
			class HideDestroyed_1_1 {
				source = "user";
				initPhase = 0;
				animPeriod = 0.001;
			};
			
			class HideDestroyed_1_2 {
				source = "user";
				initPhase = 0;
				animPeriod = 0.001;
			};
			
			class HideDestroyed_2_1 {
				source = "user";
				initPhase = 0;
				animPeriod = 0.001;
			};
			
			class HideDestroyed_2_2 {
				source = "user";
				initPhase = 0;
				animPeriod = 0.001;
			};
			
			class AnimHitWheel_1_1 {
				source = "Hit";
				hitpoint = "HitWheel_1_1";
				raw = 1;
			};
			
			class AnimHitWheel_1_2 : AnimHitWheel_1_1 {
				hitpoint = "HitWheel_1_2";
			};
			
			class AnimHitWheel_2_1 : AnimHitWheel_1_1 {
				hitpoint = "HitWheel_2_1";
			};
			
			class AnimHitWheel_2_2 : AnimHitWheel_1_1 {
				hitpoint = "HitWheel_2_2";
			};
			
			class HitDoorsHood : AnimHitWheel_1_1 {
				hitpoint = "HitDoorsHood";
			};
			
			class HitDoorsTrunk : AnimHitWheel_1_1 {
				hitpoint = "HitDoorsTrunk";
			};
			
			class HitDoorsDrivers : AnimHitWheel_1_1 {
				hitpoint = "HitDoorsDriver";
			};
			
			class HitDoorsCoDrivers : AnimHitWheel_1_1 {
				hitpoint = "HitDoorsCoDriver";
			};
			
			class HitDoorsCargo : AnimHitWheel_1_1 {
				hitpoint = "HitDoorsCargo";
			};
		};
	};
	
	class Hmmwv_M1035_Green : Hmmwv_M1035 {
		hiddenSelections[] = {"light_1_1", "light_2_1", "light_brake_1_2", "light_brake_2_2", "light_reverse_1_2", "light_reverse_2_2", "light_1_2", "light_2_2", "light_dashboard", "camo", "camo1", "camo3", "camo6"};
		hiddenSelectionsTextures[] = {"", "", "", "", "", "", "", "", "", "NM_Hmmwv\data\hmmwv_body_canvas_green_co.paa", "NM_Hmmwv\data\hmmwv_hood_canvas_green_co.paa", "NM_Hmmwv\data\hmmwv_canvas_1_green_co.paa", "NM_Hmmwv\data\hmmwv_parts_1_green_ca.paa"};
		hiddenSelectionsMaterials[] = {"", "", "", "", "", "", "", "", "", "NM_Hmmwv\data\hmmwv_body_1.rvmat", "NM_Hmmwv\data\hmmwv_hood.rvmat", "NM_Hmmwv\data\hmmwv_canvas.rvmat", "NM_Hmmwv\data\hmmwv_parts_1.rvmat"};
	};
	
	class Hmmwv_M1035_Gray : Hmmwv_M1035 {
		hiddenSelections[] = {"light_1_1", "light_2_1", "light_brake_1_2", "light_brake_2_2", "light_reverse_1_2", "light_reverse_2_2", "light_1_2", "light_2_2", "light_dashboard", "camo", "camo1", "camo3", "camo6"};
		hiddenSelectionsTextures[] = {"", "", "", "", "", "", "", "", "", "NM_Hmmwv\data\hmmwv_body_canvas_gray_co.paa", "NM_Hmmwv\data\hmmwv_hood_canvas_gray_co.paa", "NM_Hmmwv\data\hmmwv_canvas_1_gray_co.paa", "NM_Hmmwv\data\hmmwv_parts_1_gray_ca.paa"};
		hiddenSelectionsMaterials[] = {"", "", "", "", "", "", "", "", "", "NM_Hmmwv\data\hmmwv_body_1.rvmat", "NM_Hmmwv\data\hmmwv_hood.rvmat", "NM_Hmmwv\data\hmmwv_canvas.rvmat", "NM_Hmmwv\data\hmmwv_parts_1.rvmat"};
	};
	
	class Hmmwv_M1035_Black : Hmmwv_M1035 {
		hiddenSelections[] = {"light_1_1", "light_2_1", "light_brake_1_2", "light_brake_2_2", "light_reverse_1_2", "light_reverse_2_2", "light_1_2", "light_2_2", "light_dashboard", "camo", "camo1", "camo3", "camo6"};
		hiddenSelectionsTextures[] = {"", "", "", "", "", "", "", "", "", "NM_Hmmwv\data\hmmwv_body_canvas_black_co.paa", "NM_Hmmwv\data\hmmwv_hood_canvas_black_co.paa", "NM_Hmmwv\data\hmmwv_canvas_1_black_co.paa", "NM_Hmmwv\data\hmmwv_parts_1_black_ca.paa"};
		hiddenSelectionsMaterials[] = {"", "", "", "", "", "", "", "", "", "NM_Hmmwv\data\hmmwv_body_1.rvmat", "NM_Hmmwv\data\hmmwv_hood.rvmat", "NM_Hmmwv\data\hmmwv_canvas.rvmat", "NM_Hmmwv\data\hmmwv_parts_1.rvmat"};
	};
	
	class Hmmwv_M1151_M2_GPK : CarScript {
		scope = public;
		displayname = "#STR_Hmmwv_M1151_M2_GPK";
		descriptionShort = "";
		model = "\NM_Hmmwv\M1151_M2_GPK.p3d";
		InteractActions[] = {AT_GETIN_TRANSPORT};
		attachments[] = {"CarBattery", "Reflector_1_1", "Reflector_2_1", "CarRadiator", "SparkPlug", "CanisterGasoline", "Hmmwv_M1035_Wheel_1_1", "Hmmwv_M1035_Wheel_1_2", "Hmmwv_M1035_Wheel_2_1", "Hmmwv_M1035_Wheel_2_2", "Hmmwv_M1035_Wheel_spare_1", "Hmmwv_M1151_doors_Driver", "Hmmwv_M1151_Doors_coDriver", "Hmmwv_M1151_doors_cargo1", "Hmmwv_M1151_doors_cargo2", "Hmmwv_M1151_doors_trunk", "Hmmwv_M1035_doors_hood"};
		hiddenSelections[] = {"light_1_1", "light_2_1", "light_brake_1_2", "light_brake_2_2", "light_reverse_1_2", "light_reverse_2_2", "light_1_2", "light_2_2", "light_dashboard"};
		hiddenSelectionsTextures[] = {"", "", "", "", "", "", "", "", ""};
		hiddenSelectionsMaterials[] = {"", "", "", "", "", "", "", "", ""};
		dashboardMatOn = "NM_Hmmwv\data\dashboard_on.rvmat";
		dashboardMatOff = "NM_Hmmwv\data\dashboard.rvmat";
		frontReflectorMatOn = "NM_Hmmwv\data\light_on.rvmat";
		frontReflectorMatOff = "NM_Hmmwv\data\light.rvmat";
		brakeReflectorMatOn = "NM_Hmmwv\data\light_on.rvmat";
		brakeReflectorMatOff = "NM_Hmmwv\data\light.rvmat";
		ReverseReflectorMatOn = "NM_Hmmwv\data\light_on.rvmat";
		ReverseReflectorMatOff = "NM_Hmmwv\data\light.rvmat";
		TailReflectorMatOn = "dz\vehicles\wheeled\civiliansedan\data\Sedan_TailLights_e.rvmat";
		TailReflectorMatOff = "dz\vehicles\wheeled\civiliansedan\data\Sedan_TailLights.rvmat";
		weight = 1400000;
		rotationFlags = 64;
		insideSoundCoef = 0.9;
		brakeFluidCapacity = 1;
		oilCapacity = 4;
		coolantCapacity = 6;
		brakeFluidLeakDebit[] = {0, 0};
		oilLeakDebit[] = {0, 0};
		coolantLeakDebit[] = {0, 0};
		brakeFluidForceCoef[] = {0, 1, 1, 1};
		damageFromOil[] = {0, 0, 1, 0};
		damageFromCoolant[] = {0, 0, 1, 0};
		engineBeltSlot = "EngineBelt";
		batterySlot = "CarBattery";
		electricPowerResName = "power";
		electricConsumptionIgnition = 3001;
		electricConsumptionEngine = 0;
		electricConsumptionLights = 0;
		electricOutputEngine = 5;
		selectionDashboard = "light_dashboard";
		selectionLightFrontL = "light_left";
		selectionLightFrontR = "light_right";
		selectionBrakeLights = "light_break";
		fuelCapacity = 43;
		fuelConsumption = 10;
		
		class Sounds {
			thrust = 0.6;
			thrustTurbo = 1;
			thrustGentle = 0.3;
			thrustSmoothCoef = 0.1;
			camposSmoothCoef = 0.03;
			soundSetsFilter[] = {"Hmmwv_M1035_Engine_Offload_Ext_Rpm1_SoundSet", "Hmmwv_M1035_Engine_Offload_Ext_Rpm2_SoundSet", "Hmmwv_M1035_Engine_Offload_Ext_Rpm3_SoundSet", "Hmmwv_M1035_Engine_Offload_Ext_Rpm4_SoundSet", "Hmmwv_M1035_Engine_Offload_Ext_Rpm5_SoundSet", "Hmmwv_M1035_Engine_Ext_Rpm0_SoundSet", "Hmmwv_M1035_Engine_Ext_Rpm1_SoundSet", "Hmmwv_M1035_Engine_Ext_Rpm2_SoundSet", "Hmmwv_M1035_Engine_Ext_Rpm3_SoundSet", "Hmmwv_M1035_Engine_Ext_Rpm4_SoundSet", "Hmmwv_M1035_Engine_Ext_Rpm5_SoundSet", "Hmmwv_M1035_Engine_Ext_Broken_SoundSet", "offroad_Tires_rock_slow_Ext_SoundSet", "offroad_Tires_rock_fast_Ext_SoundSet", "offroad_Tires_grass_slow_Ext_SoundSet", "offroad_Tires_grass_fast_Ext_SoundSet", "offroad_Tires_gravel_slow_Ext_SoundSet", "offroad_Tires_gravel_fast_Ext_SoundSet", "offroad_Tires_asphalt_slow_Ext_SoundSet", "offroad_Tires_asphalt_fast_Ext_SoundSet", "offroad_Tires_water_slow_Ext_SoundSet", "offroad_Tires_water_fast_Ext_SoundSet", "offroad_skid_dirt_SoundSet", "offroad_dirt_turn_SoundSet", "offroad_Rain_Ext_SoundSet"};
			soundSetsInt[] = {"offroad_Tires_Asphalt_Slow_General_Int_SoundSet", "offroad_Tires_Asphalt_Fast_General_Int_SoundSet", "offroad_Wind_SoundSet"};
		};
		
		class Crew : Crew {
			class Driver : Driver {};
			
			class CoDriver : CoDriver {};
			
			class Cargo1 {
				actionSel = "seat_cargo1";
				proxyPos = "crewCargo1";
				getInPos = "pos_cargo1";
				getInDir = "pos_cargo1_dir";
			};
			
			class Cargo2 {
				actionSel = "seat_cargo2";
				proxyPos = "crewCargo2";
				getInPos = "pos_cargo2";
				getInDir = "pos_cargo2_dir";
			};
		};
		
		class SimulationModule : SimulationModule {
			drive = DRIVE_AWD;
			centralDiffRatio = 1.45;
			airDragCoefficient = 2;
			
			class Steering {
				increaseSpeed[] = {0, 45, 60, 25, 100, 15};
				decreaseSpeed[] = {0, 90, 60, 45, 100, 15};
				centeringSpeed[] = {0, 0, 15, 28, 60, 45, 100, 60};
			};
			
			class Throttle {
				reactionTime = 1.5;
				defaultThrust = 0.95;
				gentleThrust = 0.7;
				turboCoef = 4.5;
				gentleCoef = 0.76;
			};
			braking[] = {0, 0.1, 1, 0.8, 2.5, 0.9, 3, 1};
			
			class Engine {
				inertia = 0.15;
				steepness = 1.5;
				torqueMax = 320;
				torqueRpm = 3400;
				powerMax = 53.7;
				powerRpm = 5400;
				rpmIdle = 850;
				rpmMin = 900;
				rpmClutch = 1350;
				rpmRedline = 6000;
				rpmMax = 8000;
			};
			
			class Gearbox {
				reverse = 3.46;
				ratios[] = {3.667, 2.1, 1.361, 1};
				timeToUncoupleClutch = 0.15;
				timeToCoupleClutch = 0.21;
				maxClutchTorque = 250;
			};
			
			class Axles : Axles {
				class Front : Front {
					maxSteeringAngle = 40;
					finalRatio = 4.6;
					brakeBias = 0.6;
					brakeForce = 5000;
					wheelHubMass = 5;
					wheelHubRadius = 0.15;
					
					class Suspension {
						swayBar = 3000;
						stiffness = 36160;
						compression = 3400;
						damping = 7600;
						travelMaxUp = 0.3;
						travelMaxDown = 0.07;
					};
					
					class Wheels : Wheels {
						class Left : Left {
							animDamper = "damper_1_1";
							inventorySlot = "Hmmwv_M1035_Wheel_1_1";
						};
						
						class Right : Right {
							animDamper = "damper_2_1";
							inventorySlot = "Hmmwv_M1035_Wheel_2_1";
						};
					};
				};
				
				class Rear : Rear {
					maxSteeringAngle = 0;
					finalRatio = 4.6;
					brakeBias = 0.6;
					brakeForce = 4600;
					wheelHubMass = 5;
					wheelHubRadius = 0.15;
					
					class Suspension {
						swayBar = 3000;
						stiffness = 36160;
						compression = 3400;
						damping = 7600;
						travelMaxUp = 0.3;
						travelMaxDown = 0.07;
					};
					
					class Wheels : Wheels {
						class Left : Left {
							animDamper = "damper_1_2";
							inventorySlot = "Hmmwv_M1035_Wheel_1_2";
						};
						
						class Right : Right {
							animDamper = "damper_2_2";
							inventorySlot = "Hmmwv_M1035_Wheel_2_2";
						};
					};
				};
			};
		};
		
		class Cargo {
			itemsCargoSize[] = {10, 100};
			allowOwnedCargoManipulation = 1;
			openable = 0;
		};
		
		class DamageSystem {
			class GlobalHealth {
				class Health {
					hitpoints = 8700;
					healthLevels[] = {{1, {}}, {0.7, {}}, {0.5, {}}, {0.3, {}}, {0, {}}};
				};
			};
			
			class DamageZones {
				class Chassis {
					class Health {
						hitpoints = 8700;
						transferToGlobalCoef = 1;
					};
					componentNames[] = {"dmgZone_chassis"};
					fatalInjuryCoef = -1;
					inventorySlots[] = {};
				};
				
				class Front {
					class Health {
						hitpoints = 2700;
						transferToGlobalCoef = 0;
						healthLevels[] = {{1, {}}, {0.7, {}}, {0.5, {}}, {0.3, {}}, {0, {}}};
					};
					transferToZonesNames[] = {"Fender_1_1", "Fender_2_1", "Engine", "Reflector_1_1", "Reflector_2_1", "WindowFront"};
					transferToZonesThreshold[] = {0.8, 0.8, 0.5, 1, 1, 0.5};
					transferToZonesCoefs[] = {0.6, 0.6, 0.6, 0.05, 0.05};
					memoryPoints[] = {"dmgZone_front"};
					componentNames[] = {"dmgZone_front"};
					fatalInjuryCoef = -1;
					inventorySlotsCoefs[] = {0.15, 0.3};
					inventorySlots[] = {"CarRadiator", "Hmmwv_M1035_doors_hood"};
				};
				
				class Reflector_1_1 {
					class Health {
						hitpoints = 10;
						transferToGlobalCoef = 0;
						healthLevels[] = {{1, {}}, {0.7, {}}, {0.5, {}}, {0.3, {}}, {0, {}}};
					};
					transferToZonesNames[] = {"Front", "Fender_1_1", "Engine"};
					transferToZonesCoefs[] = {1, 1, 1};
					memoryPoints[] = {"dmgZone_lights_1_1"};
					componentNames[] = {"dmgZone_lights_1_1"};
					fatalInjuryCoef = -1;
					inventorySlotsCoefs[] = {1, 0.3, 0.3};
					inventorySlots[] = {"Reflector_1_1"};
				};
				
				class Reflector_2_1 : Reflector_1_1 {
					transferToZonesNames[] = {"Front", "Fender_2_1", "Engine"};
					transferToZonesCoefs[] = {1, 1, 1};
					memoryPoints[] = {"dmgZone_lights_2_1"};
					componentNames[] = {"dmgZone_lights_2_1"};
					inventorySlotsCoefs[] = {1, 0.3, 0.3};
					inventorySlots[] = {"Reflector_2_1"};
				};
				
				class Back {
					class Health {
						hitpoints = 2700;
						transferToGlobalCoef = 0;
						healthLevels[] = {{1, {}}, {0.7, {}}, {0.5, {}}, {0.3, {}}, {0, {}}};
					};
					transferToZonesNames[] = {"Fender_1_2", "Fender_2_2"};
					transferToZonesCoefs[] = {0.3, 0.3};
					memoryPoints[] = {"dmgZone_back"};
					componentNames[] = {"dmgZone_back"};
					fatalInjuryCoef = -1;
					inventorySlotsCoefs[] = {0.3};
					inventorySlots[] = {"Hmmwv_M1151_doors_trunk"};
				};
				
				class Roof {
					class Health {
						hitpoints = 2300;
						transferToGlobalCoef = 0;
						healthLevels[] = {{1, {}}, {0.7, {}}, {0.5, {}}, {0.3, {}}, {0, {}}};
					};
					memoryPoints[] = {"dmgZone_roof"};
					componentNames[] = {"dmgZone_roof"};
					fatalInjuryCoef = -1;
					inventorySlots[] = {};
				};
				
				class Fender_1_1 {
					class Health {
						hitpoints = 2400;
						transferToGlobalCoef = 0;
						healthLevels[] = {{1, {}}, {0.7, {}}, {0.5, {}}, {0.3, {}}, {0, {}}};
					};
					transferToZonesNames[] = {"Front", "Engine", "Reflector_1_1"};
					transferToZonesThreshold[] = {0.2, 0.5, 0.9};
					transferToZonesCoefs[] = {0.3, 0.6, 0.6};
					memoryPoints[] = {"dmgZone_fender_1_1"};
					componentNames[] = {"dmgZone_fender_1_1"};
					fatalInjuryCoef = -1;
					inventorySlotsCoefs[] = {0.3, 0.3, 0.3};
					inventorySlots[] = {""};
				};
				
				class Fender_2_1 : Fender_1_1 {
					transferToZonesNames[] = {"Front", "Engine", "Reflector_2_1"};
					transferToZonesThreshold[] = {0.2, 0.5, 0.9};
					transferToZonesCoefs[] = {0.3, 0.6, 0.6};
					memoryPoints[] = {"dmgZone_fender_2_1"};
					componentNames[] = {"dmgZone_fender_2_1"};
					inventorySlotsCoefs[] = {0.3, 0.2, 31};
					inventorySlots[] = {""};
				};
				
				class Fender_1_2 : Fender_1_1 {
					transferToZonesNames[] = {"Back", "FuelTank", "WindowBack"};
					transferToZonesThreshold[] = {0.2, 0.2, 0.2};
					transferToZonesCoefs[] = {0.3, 0.2, 0.7};
					memoryPoints[] = {"dmgZone_fender_1_2"};
					componentNames[] = {"dmgZone_fender_1_2"};
					inventorySlotsCoefs[] = {0.3};
					inventorySlots[] = {"Hmmwv_M1151_doors_trunk"};
				};
				
				class Fender_2_2 : Fender_1_1 {
					transferToZonesNames[] = {"Back", "FuelTank", "WindowBack"};
					transferToZonesThreshold[] = {0.2, 0.2, 0.2};
					transferToZonesCoefs[] = {0.3, 0.2, 0.7};
					memoryPoints[] = {"dmgZone_fender_2_2"};
					componentNames[] = {"dmgZone_fender_2_2"};
					inventorySlotsCoefs[] = {0.3};
					inventorySlots[] = {"Hmmwv_M1151_doors_trunk"};
				};
				
				class WindowFront {
					class Health {
						hitpoints = 300;
						transferToGlobalCoef = 0;
						healthLevels[] = {{1, {}}, {0.7, {}}, {0.5, {}}, {0.3, {}}, {0, {}}};
					};
					memoryPoints[] = {"dmgZone_windowFront"};
					componentNames[] = {"dmgZone_windowFront"};
					fatalInjuryCoef = -1;
					inventorySlots[] = {};
				};
				
				class WindowBack {
					class Health {
						hitpoints = 300;
						transferToGlobalCoef = 0;
						healthLevels[] = {{1, {}}, {0.7, {}}, {0.5, {}}, {0.3, {}}, {0, {}}};
					};
					memoryPoints[] = {"dmgZone_windowBack"};
					componentNames[] = {"dmgZone_windowBack"};
					fatalInjuryCoef = -1;
					inventorySlots[] = {};
				};
				
				class Engine {
					class Health {
						hitpoints = 8700;
						transferToGlobalCoef = 0;
						healthLevels[] = {{1, {}}, {0.7, {}}, {0.5, {}}, {0.3, {}}, {0, {}}};
					};
					memoryPoints[] = {"dmgZone_engine"};
					componentNames[] = {"dmgZone_engine"};
					fatalInjuryCoef = 0.001;
					inventorySlotsCoefs[] = {0.2, 0.2, 0.01, 0.4};
					inventorySlots[] = {};
				};
				
				class FuelTank {
					class Health {
						hitpoints = 900;
						transferToGlobalCoef = 0;
						healthLevels[] = {{1, {}}, {0.7, {}}, {0.5, {}}, {0.3, {}}, {0, {}}};
					};
					componentNames[] = {"dmgZone_fuelTank"};
					fatalInjuryCoef = -1;
					inventorySlots[] = {};
				};
				
				class Battery {
					class Health {
						hitpoints = 800;
						transferToGlobalCoef = 0;
						healthLevels[] = {{1, {}}, {0.7, {}}, {0.5, {}}, {0.3, {}}, {0, {}}};
					};
					componentNames[] = {"dmgZone_battery"};
					fatalInjuryCoef = -1;
					inventorySlots[] = {"CarBattery"};
				};
			};
		};
		
		class ObstacleGenerator {
			carve = 1;
			timeToStationary = 5;
			moveThreshold = 0.5;
			
			class Shapes {
				class Cylindric {
					class Cyl1 {
						radius = 1;
						height = 1.5;
						center[] = {0, 0, 0.7};
					};
					
					class Cyl3 {
						radius = 1;
						height = 1.5;
						center[] = {0, 0, -0.7};
					};
				};
			};
		};
		
		class GUIInventoryAttachmentsProps {
			class Engine {
				name = "#STR_Hmmwv_Engine";
				description = "";
				attachmentSlots[] = {"CarBattery", "CarRadiator", "SparkPlug", "Reflector_1_1", "Reflector_2_1"};
				icon = "cat_vehicle_engine";
			};
			
			class Body {
				name = "#STR_Hmmwv_Body";
				description = "";
				attachmentSlots[] = {"Hmmwv_M1151_doors_Driver", "Hmmwv_M1151_Doors_coDriver", "Hmmwv_M1151_doors_cargo1", "Hmmwv_M1151_doors_cargo2", "Hmmwv_M1151_doors_trunk", "Hmmwv_M1035_doors_hood"};
				icon = "cat_vehicle_body";
			};
			
			class Chassis {
				name = "#STR_Hmmwv_Chassis";
				description = "";
				attachmentSlots[] = {"Hmmwv_M1035_Wheel_1_1", "Hmmwv_M1035_Wheel_1_2", "Hmmwv_M1035_Wheel_2_1", "Hmmwv_M1035_Wheel_2_2", "Hmmwv_M1035_Wheel_spare_1"};
				icon = "cat_vehicle_chassis";
			};
			
			class Attachments {
				name = "#STR_Hmmwv_Attachments";
				description = "";
				attachmentSlots[] = {"CanisterGasoline"};
				icon = "cat_vehicle_chassis";
			};
		};
		
		class AnimationSources {
			class DoorsDriver {
				source = "user";
				initPhase = 0;
				animPeriod = 0.5;
			};
			
			class DoorsCoDriver : DoorsDriver {};
			
			class DoorsHood : DoorsDriver {};
			
			class DoorsTrunk : DoorsDriver {};
			
			class DoorsCargo1 : DoorsDriver {};
			
			class DoorsCargo2 : DoorsDriver {};
			
			class HideDestroyed_1_1 {
				source = "user";
				initPhase = 0;
				animPeriod = 0.001;
			};
			
			class HideDestroyed_1_2 {
				source = "user";
				initPhase = 0;
				animPeriod = 0.001;
			};
			
			class HideDestroyed_2_1 {
				source = "user";
				initPhase = 0;
				animPeriod = 0.001;
			};
			
			class HideDestroyed_2_2 {
				source = "user";
				initPhase = 0;
				animPeriod = 0.001;
			};
			
			class AnimHitWheel_1_1 {
				source = "Hit";
				hitpoint = "HitWheel_1_1";
				raw = 1;
			};
			
			class AnimHitWheel_1_2 : AnimHitWheel_1_1 {
				hitpoint = "HitWheel_1_2";
			};
			
			class AnimHitWheel_2_1 : AnimHitWheel_1_1 {
				hitpoint = "HitWheel_2_1";
			};
			
			class AnimHitWheel_2_2 : AnimHitWheel_1_1 {
				hitpoint = "HitWheel_2_2";
			};
			
			class HitDoorsHood : AnimHitWheel_1_1 {
				hitpoint = "HitDoorsHood";
			};
			
			class HitDoorsTrunk : AnimHitWheel_1_1 {
				hitpoint = "HitDoorsTrunk";
			};
			
			class HitDoorsDrivers : AnimHitWheel_1_1 {
				hitpoint = "HitDoorsDriver";
			};
			
			class HitDoorsCoDrivers : AnimHitWheel_1_1 {
				hitpoint = "HitDoorsCoDriver";
			};
			
			class HitDoorsCargo : AnimHitWheel_1_1 {
				hitpoint = "HitDoorsCargo";
			};
		};
	};
	
	class Hmmwv_M1151_M2_GPK_Green : Hmmwv_M1151_M2_GPK {
		hiddenSelections[] = {"light_1_1", "light_2_1", "light_brake_1_2", "light_brake_2_2", "light_reverse_1_2", "light_reverse_2_2", "light_1_2", "light_2_2", "light_dashboard", "camo", "camo1", "camo3", "camo2"};
		hiddenSelectionsTextures[] = {"", "", "", "", "", "", "", "", "", "NM_Hmmwv\data\hmmwv_body_canvas_green_co.paa", "NM_Hmmwv\data\hmmwv_hood_canvas_green_co.paa", "NM_Hmmwv\data\hmmwv_gpk_tower_green_co.paa", "NM_Hmmwv\data\hmmwv_regular_1_green_co.paa"};
		hiddenSelectionsMaterials[] = {"", "", "", "", "", "", "", "", "", "NM_Hmmwv\data\hmmwv_body_1.rvmat", "NM_Hmmwv\data\hmmwv_hood.rvmat", "NM_Hmmwv\data\hmmwv_gpk_tower.rvmat", "NM_hmmwv\data\hmmwv_regular_gpk.rvmat"};
	};
	
	class Hmmwv_M1151_M2_GPK_Gray : Hmmwv_M1151_M2_GPK {
		hiddenSelections[] = {"light_1_1", "light_2_1", "light_brake_1_2", "light_brake_2_2", "light_reverse_1_2", "light_reverse_2_2", "light_1_2", "light_2_2", "light_dashboard", "camo", "camo1", "camo3", "camo2"};
		hiddenSelectionsTextures[] = {"", "", "", "", "", "", "", "", "", "NM_Hmmwv\data\hmmwv_body_canvas_gray_co.paa", "NM_Hmmwv\data\hmmwv_hood_canvas_gray_co.paa", "NM_Hmmwv\data\hmmwv_gpk_tower_gray_co.paa", "NM_Hmmwv\data\hmmwv_regular_1_gray_co.paa"};
		hiddenSelectionsMaterials[] = {"", "", "", "", "", "", "", "", "", "NM_Hmmwv\data\hmmwv_body_1.rvmat", "NM_Hmmwv\data\hmmwv_hood.rvmat", "NM_Hmmwv\data\hmmwv_gpk_tower.rvmat", "NM_hmmwv\data\hmmwv_regular_gpk.rvmat"};
	};
	
	class Hmmwv_M1151_M2_GPK_Black : Hmmwv_M1151_M2_GPK {
		hiddenSelections[] = {"light_1_1", "light_2_1", "light_brake_1_2", "light_brake_2_2", "light_reverse_1_2", "light_reverse_2_2", "light_1_2", "light_2_2", "light_dashboard", "camo", "camo1", "camo3", "camo2"};
		hiddenSelectionsTextures[] = {"", "", "", "", "", "", "", "", "", "NM_Hmmwv\data\hmmwv_body_canvas_black_co.paa", "NM_Hmmwv\data\hmmwv_hood_canvas_black_co.paa", "NM_Hmmwv\data\hmmwv_gpk_tower_black_co.paa", "NM_Hmmwv\data\hmmwv_regular_1_black_co.paa"};
		hiddenSelectionsMaterials[] = {"", "", "", "", "", "", "", "", "", "NM_Hmmwv\data\hmmwv_body_1.rvmat", "NM_Hmmwv\data\hmmwv_hood.rvmat", "NM_Hmmwv\data\hmmwv_gpk_tower.rvmat", "NM_hmmwv\data\hmmwv_regular_gpk.rvmat"};
	};
};

class CfgNonAIVehicles {
	class ProxyAttachment;	// External class reference
	
	class ProxyVehiclePart : ProxyAttachment {
		scope = public;
		simulation = "ProxyInventory";
		autocenter = false;
		animated = false;
		shadow = true;
		reversed = false;
	};
	
	class ProxyHmmwv_M1035_Wheel : ProxyVehiclePart {
		model = "NM_Hmmwv\proxy\Hmmwv_M1035_Wheel.p3d";
		inventorySlot[] = {"Hmmwv_M1035_Wheel_1_1", "Hmmwv_M1035_Wheel_1_2", "Hmmwv_M1035_Wheel_2_1", "Hmmwv_M1035_Wheel_2_2", "Hmmwv_M1035_Wheel_spare_1"};
	};
	
	class ProxyHmmwv_M1035_Wheel_destroyed : ProxyVehiclePart {
		model = "NM_Hmmwv\proxy\Hmmwv_M1035_Wheel_destroyed.p3d";
		inventorySlot[] = {"Hmmwv_M1035_Wheel_1_1", "Hmmwv_M1035_Wheel_1_2", "Hmmwv_M1035_Wheel_2_1", "Hmmwv_M1035_Wheel_2_2", "Hmmwv_M1035_Wheel_spare_1"};
	};
	
	class ProxyHmmwv_M1035_doors_Driver : ProxyVehiclePart {
		model = "NM_Hmmwv\proxy\Hmmwv_M1035_doors_Driver.p3d";
		inventorySlot = "Hmmwv_M1035_doors_Driver";
	};
	
	class ProxyHmmwv_M1035_Doors_coDriver : ProxyVehiclePart {
		model = "NM_Hmmwv\proxy\Hmmwv_M1035_Doors_coDriver.p3d";
		inventorySlot = "Hmmwv_M1035_Doors_coDriver";
	};
	
	class ProxyHmmwv_M1035_doors_cargo1 : ProxyVehiclePart {
		model = "NM_Hmmwv\proxy\Hmmwv_M1035_doors_cargo1.p3d";
		inventorySlot = "Hmmwv_M1035_doors_cargo1";
	};
	
	class ProxyHmmwv_M1035_doors_cargo2 : ProxyVehiclePart {
		model = "NM_Hmmwv\proxy\Hmmwv_M1035_doors_cargo2.p3d";
		inventorySlot = "Hmmwv_M1035_doors_cargo2";
	};
	
	class ProxyHmmwv_M1035_doors_hood : ProxyVehiclePart {
		model = "NM_Hmmwv\proxy\Hmmwv_M1035_doors_hood.p3d";
		inventorySlot = "Hmmwv_M1035_doors_hood";
	};
	
	class ProxyHmmwv_M1151_doors_Driver : ProxyVehiclePart {
		model = "NM_Hmmwv\proxy\Hmmwv_M1151_doors_Driver.p3d";
		inventorySlot = "Hmmwv_M1151_doors_Driver";
	};
	
	class ProxyHmmwv_M1151_Doors_coDriver : ProxyVehiclePart {
		model = "NM_Hmmwv\proxy\Hmmwv_M1151_Doors_coDriver.p3d";
		inventorySlot = "Hmmwv_M1151_Doors_coDriver";
	};
	
	class ProxyHmmwv_M1151_doors_cargo1 : ProxyVehiclePart {
		model = "NM_Hmmwv\proxy\Hmmwv_M1151_doors_cargo1.p3d";
		inventorySlot = "Hmmwv_M1151_doors_cargo1";
	};
	
	class ProxyHmmwv_M1151_doors_cargo2 : ProxyVehiclePart {
		model = "NM_Hmmwv\proxy\Hmmwv_M1151_doors_cargo2.p3d";
		inventorySlot = "Hmmwv_M1151_doors_cargo2";
	};
	
	class ProxyHmmwv_M1151_doors_trunk : ProxyVehiclePart {
		model = "NM_Hmmwv\proxy\Hmmwv_M1151_doors_trunk.p3d";
		inventorySlot = "Hmmwv_M1151_doors_trunk";
	};
	
	class ProxyJerryCan : ProxyVehiclePart {
		model = "\dz\vehicles\parts\JerryCan.p3d";
		inventorySlot = "CanisterGasoline";
	};
	
	class ProxyPart {
		scope = public;
		simulation = "ProxyInventory";
		model = "";
		inventorySlot = "";
		autocenter = false;
		animated = false;
		shadow = true;
		reversed = true;
	};
};

class CfgSoundShaders {
	class baseEngineHmmwv_M1035_SoundShader {
		range = 80;
	};
	
	class Hmmwv_M1035_Engine_Ext_Rpm0_SoundShader : baseEngineHmmwv_M1035_SoundShader {
		samples[] = {{"NM_Hmmwv\sounds\Hmmwv_M1035_Engine_Ext_Rpm0", 1}};
		frequency = "1 * ((850 + ((rpm - 850)/(8000/5600))) max 850) / 850";
		volume = "0.75 * 1 * engineOn * 0.4 * ((850 + ((rpm - 850)/(8000/5600))) factor [(((850+1200)/2) + 2.5*50),(((850+1200)/2) - 50)]) * ((1 - 0.25*doors) max campos)";
	};
	
	class Hmmwv_M1035_Engine_Ext_Rpm1_SoundShader : baseEngineHmmwv_M1035_SoundShader {
		samples[] = {{"NM_Hmmwv\sounds\Hmmwv_M1035_Engine_Ext_Rpm1", 2}};
		frequency = "1 * (850 + ((rpm - 850)/(8000/5600))) / 1200";
		volume = "0.75 * 1 * (thrust factor[0.1,0.45]) * (0.7 + 0.3 * (speed factor [10,60])) * engineOn * 0.6 * ((850 + ((rpm - 850)/(8000/5600))) factor [(((850+1200)/2) - 2.5*50),(((850+1200)/2) + 50)]) * ((850 + ((rpm - 850)/(8000/5600))) factor [(((1200+1700)/2) + 2.5*150),(((1200+1700)/2) - 150)]) * ((1 - 0.25*doors) max campos)";
	};
	
	class Hmmwv_M1035_Engine_Offload_Ext_Rpm1_SoundShader : baseEngineHmmwv_M1035_SoundShader {
		samples[] = {{"NM_Hmmwv\sounds\Hmmwv_M1035_Engine_Ext_Offload_Rpm1", 2}};
		frequency = "1 * (850 + ((rpm - 850)/(8000/5600))) / 1200";
		volume = "0.75 * 1 * (thrust factor[0.6,0.2]) * (0.7 + 0.3 * (speed factor [10,60])) * engineOn * 0.6 * ((850 + ((rpm - 850)/(8000/5600))) factor [(((850+1200)/2) - 2.5*50),(((850+1200)/2) + 50)]) * ((850 + ((rpm - 850)/(8000/5600))) factor [(((1200+1700)/2) + 2.5*150),(((1200+1700)/2) - 150)]) * ((1 - 0.25*doors) max campos)";
	};
	
	class Hmmwv_M1035_Engine_Ext_Rpm2_SoundShader : baseEngineHmmwv_M1035_SoundShader {
		samples[] = {{"NM_Hmmwv\sounds\Hmmwv_M1035_Engine_Ext_Rpm2", 2}};
		frequency = "1 * (850 + ((rpm - 850)/(8000/5600))) / 1700";
		volume = "0.75 * 1 * (thrust factor[0.1,0.45]) * (0.7 + 0.3 * (speed factor [10,60])) * engineOn * 0.85 * ((850 + ((rpm - 850)/(8000/5600))) factor [(((1200+1700)/2) - 2.5*150),(((1200+1700)/2) + 150)]) * ((850 + ((rpm - 850)/(8000/5600))) factor [(((1700+2300)/2) + 2.5*150),(((1700+2300)/2) - 150)]) * ((1 - 0.25*doors) max campos)";
	};
	
	class Hmmwv_M1035_Engine_Offload_Ext_Rpm2_SoundShader : baseEngineHmmwv_M1035_SoundShader {
		samples[] = {{"NM_Hmmwv\sounds\Hmmwv_M1035_Engine_Ext_Offload_Rpm2", 2}};
		frequency = "1 * (850 + ((rpm - 850)/(8000/5600))) / 1700";
		volume = "0.75 * 1 * (thrust factor[0.6,0.2]) * (0.7 + 0.3 * (speed factor [10,60])) * engineOn * 0.85 * ((850 + ((rpm - 850)/(8000/5600))) factor [(((1200+1700)/2) - 2.5*150),(((1200+1700)/2) + 150)]) * ((850 + ((rpm - 850)/(8000/5600))) factor [(((1700+2300)/2) + 2.5*150),(((1700+2300)/2) - 150)]) * ((1 - 0.25*doors) max campos)";
	};
	
	class Hmmwv_M1035_Engine_Ext_Rpm3_SoundShader : baseEngineHmmwv_M1035_SoundShader {
		samples[] = {{"NM_Hmmwv\sounds\Hmmwv_M1035_Engine_Ext_Rpm3", 2}};
		frequency = "1 * (850 + ((rpm - 850)/(8000/5600))) / 2300";
		volume = "0.75 * 1 * (thrust factor[0.1,0.45]) * (0.7 + 0.3 * (speed factor [10,60])) * engineOn * 1 * ((850 + ((rpm - 850)/(8000/5600))) factor [(((1700+2300)/2) - 2.5*150),(((1700+2300)/2) + 150)]) * ((850 + ((rpm - 850)/(8000/5600))) factor [(((2300+3150)/2) + 2.5*200),(((2300+3150)/2) - 200)]) * ((1 - 0.25*doors) max campos)";
	};
	
	class Hmmwv_M1035_Engine_Offload_Ext_Rpm3_SoundShader : baseEngineHmmwv_M1035_SoundShader {
		samples[] = {{"NM_Hmmwv\sounds\Hmmwv_M1035_Engine_Ext_Offload_Rpm3", 2}};
		frequency = "1 * (850 + ((rpm - 850)/(8000/5600))) / 2300";
		volume = "0.75 * 1 * (thrust factor[0.6,0.2]) * (0.7 + 0.3 * (speed factor [10,60])) * engineOn * 1 * ((850 + ((rpm - 850)/(8000/5600))) factor [(((1700+2300)/2) - 2.5*150),(((1700+2300)/2) + 150)]) * ((850 + ((rpm - 850)/(8000/5600))) factor [(((2300+3150)/2) + 2.5*200),(((2300+3150)/2) - 200)]) * ((1 - 0.25*doors) max campos)";
	};
	
	class Hmmwv_M1035_Engine_Ext_Rpm4_SoundShader : baseEngineHmmwv_M1035_SoundShader {
		samples[] = {{"NM_Hmmwv\sounds\Hmmwv_M1035_Engine_Ext_Rpm4", 2}};
		frequency = "1 * (850 + ((rpm - 850)/(8000/5600))) / 3150";
		volume = "0.75 * 1 * (thrust factor[0.1,0.45]) * (0.7 + 0.3 * (speed factor [10,60])) * engineOn * 1 * ((850 + ((rpm - 850)/(8000/5600))) factor [(((2300+3150)/2) - 2.5*200),(((2300+3150)/2) + 200)]) * ((850 + ((rpm - 850)/(8000/5600))) factor [(((3150+4400)/2) + 2.5*200),(((3150+4400)/2) - 200)]) * ((1 - 0.25*doors) max campos)";
	};
	
	class Hmmwv_M1035_Engine_Offload_Ext_Rpm4_SoundShader : baseEngineHmmwv_M1035_SoundShader {
		samples[] = {{"NM_Hmmwv\sounds\Hmmwv_M1035_Engine_Ext_Offload_Rpm4", 2}};
		frequency = "1 * (850 + ((rpm - 850)/(8000/5600))) / 3150";
		volume = "0.75 * 1 * (thrust factor[0.6,0.2]) * (0.7 + 0.3 * (speed factor [10,60])) * engineOn * 1 * ((850 + ((rpm - 850)/(8000/5600))) factor [(((2300+3150)/2) - 2.5*200),(((2300+3150)/2) + 200)]) * ((850 + ((rpm - 850)/(8000/5600))) factor [(((3150+4400)/2) + 2.5*200),(((3150+4400)/2) - 200)]) * ((1 - 0.25*doors) max campos)";
	};
	
	class Hmmwv_M1035_Engine_Ext_Rpm5_SoundShader : baseEngineHmmwv_M1035_SoundShader {
		samples[] = {{"NM_Hmmwv\sounds\Hmmwv_M1035_Engine_Ext_Rpm5", 2}};
		frequency = "(1 * (850 + ((rpm - 850)/(8000/5600))) / 4400) min (8000/5600)";
		volume = "0.75 * 1 * (thrust factor[0.1,0.45]) * (0.7 + 0.3 * (speed factor [10,60])) * engineOn * 1 * ((850 + ((rpm - 850)/(8000/5600))) factor [(((3150+4400)/2) - 2.5*200),(((3150+4400)/2) + 200)]) * ((1 - 0.25*doors) max campos)";
	};
	
	class Hmmwv_M1035_Engine_Offload_Ext_Rpm5_SoundShader : baseEngineHmmwv_M1035_SoundShader {
		samples[] = {{"NM_Hmmwv\sounds\Hmmwv_M1035_Engine_Ext_Offload_Rpm5", 2}};
		frequency = "(1 * (850 + ((rpm - 850)/(8000/5600))) / 4400) min (8000/5600)";
		volume = "0.75 * 1 * (thrust factor[0.6,0.2]) * (0.7 + 0.3 * (speed factor [10,60])) * engineOn * 1 * ((850 + ((rpm - 850)/(8000/5600))) factor [(((3150+4400)/2) - 2.5*200),(((3150+4400)/2) + 200)]) * ((1 - 0.25*doors) max campos)";
	};
	
	class Hmmwv_M1035_Engine_Ext_Broken_SoundShader : baseEngineHmmwv_M1035_SoundShader {
		samples[] = {{"NM_Hmmwv\sounds\Hmmwv_M1035_Engine_Ext_Broken", 2}};
		frequency = 0.9;
		volume = "0.75 * 1 * (0.7 + 0.3 * (speed factor [10,60])) * engineOn * 1 * ((850 + ((rpm - 850)/(8000/5600))) factor [(((3150+4400)/2) - 2.5*200),(((3150+4400)/2) + 200)]) * ((1 - 0.25*doors) max campos) * (rpm factor[4800,6200])";
	};
};

class CfgSoundSets {
	class baseEngine_EXT_SoundSet {
		sound3DProcessingType = "Vehicle_Ext_3DProcessingType";
		distanceFilter = "softVehiclesDistanceFreqAttenuationFilter";
		volumeCurve = "vehicleEngineAttenuationCurve";
		volumeFactor = 1;
		spatial = 1;
		loop = 1;
	};
	
	class Hmmwv_M1035_Engine_Ext_Rpm0_SoundSet : baseEngine_EXT_SoundSet {
		soundShaders[] = {"Hmmwv_M1035_Engine_Ext_Rpm0_SoundShader"};
		volumeFactor = 1;
	};
	
	class Hmmwv_M1035_Engine_Offload_Ext_Rpm1_SoundSet : baseEngine_EXT_SoundSet {
		soundShaders[] = {"Hmmwv_M1035_Engine_Offload_Ext_Rpm1_SoundShader"};
		volumeFactor = 1;
	};
	
	class Hmmwv_M1035_Engine_Ext_Rpm1_SoundSet : baseEngine_EXT_SoundSet {
		soundShaders[] = {"Hmmwv_M1035_Engine_Ext_Rpm1_SoundShader"};
		volumeFactor = 1;
	};
	
	class Hmmwv_M1035_Engine_Ext_Rpm2_SoundSet : baseEngine_EXT_SoundSet {
		soundShaders[] = {"Hmmwv_M1035_Engine_Ext_Rpm2_SoundShader"};
		volumeFactor = 1;
	};
	
	class Hmmwv_M1035_Engine_Offload_Ext_Rpm2_SoundSet : baseEngine_EXT_SoundSet {
		soundShaders[] = {"Hmmwv_M1035_Engine_Offload_Ext_Rpm2_SoundShader"};
		volumeFactor = 1;
	};
	
	class Hmmwv_M1035_Engine_Ext_Rpm3_SoundSet : baseEngine_EXT_SoundSet {
		soundShaders[] = {"Hmmwv_M1035_Engine_Ext_Rpm3_SoundShader"};
		volumeFactor = 1;
	};
	
	class Hmmwv_M1035_Engine_Offload_Ext_Rpm3_SoundSet : baseEngine_EXT_SoundSet {
		soundShaders[] = {"Hmmwv_M1035_Engine_Offload_Ext_Rpm3_SoundShader"};
		volumeFactor = 1;
	};
	
	class Hmmwv_M1035_Engine_Ext_Rpm4_SoundSet : baseEngine_EXT_SoundSet {
		soundShaders[] = {"Hmmwv_M1035_Engine_Ext_Rpm4_SoundShader"};
		volumeFactor = 1;
	};
	
	class Hmmwv_M1035_Engine_Offload_Ext_Rpm4_SoundSet : baseEngine_EXT_SoundSet {
		soundShaders[] = {"Hmmwv_M1035_Engine_Offload_Ext_Rpm4_SoundShader"};
		volumeFactor = 1;
	};
	
	class Hmmwv_M1035_Engine_Ext_Rpm5_SoundSet : baseEngine_EXT_SoundSet {
		soundShaders[] = {"Hmmwv_M1035_Engine_Ext_Rpm5_SoundShader"};
		volumeFactor = 1;
	};
	
	class Hmmwv_M1035_Engine_Offload_Ext_Rpm5_SoundSet : baseEngine_EXT_SoundSet {
		soundShaders[] = {"Hmmwv_M1035_Engine_Offload_Ext_Rpm5_SoundShader"};
		volumeFactor = 1;
	};
	
	class Hmmwv_M1035_Engine_Ext_Broken_SoundSet : baseEngine_EXT_SoundSet {
		soundShaders[] = {"Hmmwv_M1035_Engine_Ext_Broken_SoundShader"};
		volumeFactor = 1;
	};
};
